// Generated by core/build.mjs from film.components. Edit the component files.
import type {ComponentType} from 'react';
import type {ShotProps} from './types';
import ContinuousExample from "./shots/ContinuousExample";

export const registry: Record<string,ComponentType<ShotProps>> = {"ContinuousExample": ContinuousExample,
};
